# Latex-Online container
#
# VERSION       1

# use the ubuntu base image provided by dotCloud
FROM node:8.9.1-stretch

MAINTAINER yang wesley

# Sorted list of used packages.
RUN apt-get clean && apt-get update && apt-get install -y \
    biber \
    cm-super \
    fontconfig \
    git-core \
    latex-xcolor \
    preview-latex-style \
    python3 \
    texlive-bibtex-extra \
    texlive-fonts-extra \
    texlive-generic-extra \
    texlive-lang-all \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-math-extra \
    texlive-publishers \
    texlive-science \
    texlive-xetex \ 
    texlive-latex-recommended \
    texlive-fonts-recommended \
    texlive-font-utils \
    texlive-lang-chinese \
    texlive-pictures \
    ttf-wqy-microhei \ 
    ttf-wqy-zenhei \
    xfonts-wqy

# Add xindy-2.2 instead of makeindex.
ADD ./packages/xindy-2.2-rc2-linux.tar.gz /opt
ADD ./fonts/* /usr/share/fonts/
ENV PATH="/opt/xindy-2.2/bin:${PATH}"

COPY ./util/docker-entrypoint.sh /

EXPOSE 2700
CMD ["./docker-entrypoint.sh"]

